databases:
  - name: books_shopping_app_api
    databaseName: books_shopping_app_api
    user: books_shopping_app_api
    plan: free

services:
  - type: web
    name: books_shopping_app_api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: books_shopping_app_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
